defaults:
  notify_email: admin@boxcarpress.com
  from_email: sslwatch@boxcarpress.com
  subject: '[Webserver] Your certificate report'
  debug: 2

system:
  log_file: '/var/log/pysslwatch.log'
  conf_location: '/etc/nginx/conf.d'
  server: 'nginx'
  openssl: '/usr/bin/openssl'

ignore:
  confs:
    - parked.conf
    - auth
  domains:
    - boxcarpress.com
    - smockpaper.com
